# Generated by Django 3.2 on 2021-04-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0003_auto_20210401_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tigID', models.IntegerField(default='-1')),
                ('name', models.CharField(max_length=2000)),
                ('category', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('unit', models.CharField(max_length=2000)),
                ('availability', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('discount', models.FloatField(default=0.0)),
                ('comments', models.CharField(max_length=2000)),
                ('owner', models.CharField(max_length=2000)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
