# Generated by Django 3.2 on 2021-04-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0004_produit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='discount',
            new_name='discount_percent',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='category',
            new_name='sales_number',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='unit',
        ),
        migrations.AddField(
            model_name='produit',
            name='discount_price',
            field=models.FloatField(default=0.0),
        ),
    ]
