# Generated by Django 3.2 on 2021-04-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0005_auto_20210415_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='category',
            field=models.IntegerField(default='-1'),
        ),
    ]
