# Generated by Django 3.2 on 2021-04-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0006_produit_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0.0)),
                ('tigID', models.IntegerField(default='-1')),
                ('transaction_type', models.IntegerField(default='-1')),
            ],
        ),
    ]
